name: Build and Deploy Streamlit OCR App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy app using ZipDeploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: AFGCustomerService  # Your Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
