name: Build and Deploy Streamlit OCR App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/webapps-deploy@v2
        with:
          app-name: AFG-CustomerService # (this is your Azure App Service name)
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: my-streamlit-app

      - name: Build Docker Image
        run: |
          docker build -t my-streamlit-app .
