name: Build and Deploy Tesseract OCR App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Pull your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: afgcontreg1.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 3: Build and Push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t afgcontreg1.azurecr.io/customer-service-ai:latest .
          docker push afgcontreg1.azurecr.io/customer-service-ai:latest


      # Step 4: Deploy Docker image to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: AFG-CustomerService
          images: afgcontreg1.azurecr.io/customer-service-ai
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
