# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AFG-CustomerService

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://afgcontreg1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_26feef45da6d460d93e3cec7043a03ac }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c8119be7252e4a6988ef3e859515ef4d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: afgcontreg1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_26feef45da6d460d93e3cec7043a03ac }}/customer-service-ai:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AFG-CustomerService'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f53a217ec56a4bd2b0158f20812d4a42 }}
        images: 'afgcontreg1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_26feef45da6d460d93e3cec7043a03ac }}/customer-service-ai:${{ github.sha }}'